
package org.jboss.spring.examples.primrose.wstest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-07/27/2010 07:03 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WateringService", targetNamespace = "http://ws.primrose.examples.spring.jboss.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WateringService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifyWatering", targetNamespace = "http://ws.primrose.examples.spring.jboss.org/", className = "org.jboss.spring.examples.primrose.wstest.NotifyWatering")
    @ResponseWrapper(localName = "notifyWateringResponse", targetNamespace = "http://ws.primrose.examples.spring.jboss.org/", className = "org.jboss.spring.examples.primrose.wstest.NotifyWateringResponse")
    public void notifyWatering(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1);

}
