
package org.jboss.spring.examples.primrose.wstest;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-07/27/2010 07:03 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WateringServiceService", targetNamespace = "http://ws.primrose.examples.spring.jboss.org/", wsdlLocation = "file:/home/kpiwko/devel/primrose/test-ws/src/main/resources/WateringServiceService.wsdl")
public class WateringServiceService
    extends Service
{

    private final static URL WATERINGSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.jboss.spring.examples.primrose.wstest.WateringServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.jboss.spring.examples.primrose.wstest.WateringServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/kpiwko/devel/primrose/test-ws/src/main/resources/WateringServiceService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/kpiwko/devel/primrose/test-ws/src/main/resources/WateringServiceService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WATERINGSERVICESERVICE_WSDL_LOCATION = url;
    }

    public WateringServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WateringServiceService() {
        super(WATERINGSERVICESERVICE_WSDL_LOCATION, new QName("http://ws.primrose.examples.spring.jboss.org/", "WateringServiceService"));
    }

    /**
     * 
     * @return
     *     returns WateringService
     */
    @WebEndpoint(name = "WateringServicePort")
    public WateringService getWateringServicePort() {
        return super.getPort(new QName("http://ws.primrose.examples.spring.jboss.org/", "WateringServicePort"), WateringService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WateringService
     */
    @WebEndpoint(name = "WateringServicePort")
    public WateringService getWateringServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.primrose.examples.spring.jboss.org/", "WateringServicePort"), WateringService.class, features);
    }

}
